<div class="container">
  <div class="form-border col-12 col-sm-12 border">
    <form action="<?php echo isset($this->produto->id) ? '' : '/produtos/cadastrar'?>" method="post" accept-charset="utf-8" class="form-content border">
      <h2 class="text-left"><?php echo $this->titleHeader?></h2>
      <hr>
      <div class="form-row">
        <div class="col-md-8">
          <input type="text" name="nome" placeholder="Produto" autofocus required class="form-control" 
          value="<?php echo $this->produto->nome ?>">
        </div>
        <div class="col-md-4">
          <select class="form-control" name="id_und_medida" autofocus required>
            <?php
              $selected = !isset($this->produto->id)? "selected ": "";
              $options = "<option value='' {$selected} hidden>und medida</option>";
              
              foreach ($this->undMedidas as $undMedida) {
                $selected = $undMedida->ativo ? "selected": "";
                $options .= "<option value='{$undMedida->id}' {$selected}>{$undMedida->unidade}</option>";
              }
              
              echo $options;
            ?>
          </select>
        </div>
        <div class="col-md-12" style="padding-top: 10px;">
          <textarea type="text" name="descricao" placeholder="Descrição" class="form-control"><?php echo $this->produto->descricao ?></textarea>
        </div>
        <div class="col-md-2">
          <button type="submit" name="acaoAndIdUser" value="<?php echo $this->produto->id ?>" class="btn btn-danger btn-block mt-3 btn-center">
              <?php echo isset($this->produto->id) ? 'Alterar' : 'Cadastrar <span class="fa fa-save"></span>'; ?>
          </button>
        </div>
        <div class="col-md-2">
          <a href="/produtos" class="btn btn-danger btn-block mt-3 btn-center">
              Cancelar
              <span class="fa fa-times"></span>
          </a>
        </div>
      </div>      
    </form>
</div>