<div class="container">
  <div class="row header-pager">
    <div class="col-11">
      <h1>Produtos</h1>
    </div>
    <div class="col-1">
      <a data-toggle='tooltip' title='Cadastrar' href='/produtos/cadastrar'>
        <button type='submit' name='alterar' class='btn btn-danger mt-3'>
          <span class="fa fa-plus"></span>
        </button>
      </a>
    </div>
  </div>
  <hr/>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
        <th scope="col">Nº</th>
        <th scope="col">Nome</th>
        <th scope="col">Und medida</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>    
        <?php 
          $i = 0;

          foreach ($this->listaProdutos as $produto) {
            $btnAlterar = "<a data-toggle='tooltip' title='Editar' href='/produtos/$produto->id/atualizar'
                              name='alterar' class='btn btn-danger btn-block'>
                              <span class='fa fa-pencil'></span>
                           </a>";
            $btnExcluir = "<a data-toggle='tooltip' title='Excluir' href='/produtos/$produto->id/excluir'
                              name='excluir' class='btn btn-danger btn-block'>
                              <span class='fa fa-trash'></span>
                           </a>";
            $i++;

            echo "
            <tr>
              <td> <b>$i</b></td>
              <td>$produto->nome</td>
              <td>$produto->und_medida</td>
              <td width='5%'>$btnAlterar</td>
              <td width='5%'>$btnExcluir</td>
            </tr>";
          }
        ?>
    </tbody>
  </table>
        </div>
</div>