<div class="container">
  <div class="row header-pager">
    <div class="col-6">
      <h1>Usuários</h1>
    </div>
    <div class="col-6">
      <a href='/produtos/cadastrar'>
        <button type='submit' name='alterar' class='btn btn-danger right-button'>
          Cadastrar
          <span class="fa fa-save"></span>
        </button>
      </a>
    </div>
  </div>
  <hr>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Função</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
         <?php 
          $i = 0;

          //foreach ($this->listaProdutos as $produto) {
            $btnAlterar = "<a href=''
                            <button type='submit' name='alterar' class='btn btn-danger btn-block'>
                              Alterar
                            </button>
                           </a>";

        
            $i++;

            echo "
            <tr>
              <td>Matheus Oliveira Paixão</td>
              <td>Tesoureiro</td>
              <td width='10%'>$btnAlterar</td>
            </tr>";
         // }
        ?>
    </tbody>
  </table>
</div>