<div class="container">
  <div class="row header-pager">
    <div class="col-11">
      <h1>Usuários</h1>
    </div>
    <div class="col-1">
      <a data-toggle='tooltip' title='Cadastrar novo usuário' href='/usuario/cadastrar' class='btn btn-danger mt-3'>
        <span class="fa fa-plus"></span>
      </a>
    </div>
  </div>
  <hr>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Usuário</th>
        <th scope="col">Ultimo acesso</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
         <?php 
          foreach ($this->usuarios as $usuario) {
            $btnDados = "<a data-toggle='tooltip' title='Visualizar dados' href='/perfil/$usuario->id'
                            name='dados' class='btn btn-danger btn-block'>
                            <span class='fa fa-database'></span>
                        </a>";
            echo "
            <tr>
              <td>$usuario->nome</td>
              <td>$usuario->login</td>
              <td>$usuario->ultimo_acesso</td>
              <td width='5%'>$btnDados</td>
            </tr>";
          }
        ?>
    </tbody>
  </table>
  </div>
</div>