<div class="container">
  <div class="row header-pager">
    <div class="col-6">
      <h1>Aprovar Orçamentos</h1>
    </div>
  </div>
  <hr>
  <div style="overflow-x:auto;">
  <table class="table table-striped ">
    <thead>
      <tr>
        <td colspan="3" align="center"><b>Orçamento 0001</b></td>
        <th scope="col">Fornecedora 1</th>
        <th scope="col">Fornecedora 2</th>
        <th scope="col">Fornecedora 1</th>
        <th scope="col">Fornecedora 2</th>
      </tr>
      <tr>
        <th scope="col">Produto</th>
        <th scope="col">Und</th>
        <th scope="col">Qtd</th>
        <th scope="col">Valor Proposto</th>
        <th scope="col">Valor Proposto</th>
        <th scope="col">Valor Proposto</th>
        <th scope="col">Valor Proposto</th>
      </tr>
    </thead>
    <tbody>
            <tr>
              <td>Cimento</td>
              <td>Saca</td>
              <td>25</td>
              <td>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                  <label class="form-check-label" for="inlineRadio2">R$ 625,00</label>
                  </div>
              </td>
              <td>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                  <label class="form-check-label" for="inlineRadio2">R$ 619,00</label>
                </div>
              </td>
              <td>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                  <label class="form-check-label" for="inlineRadio2">R$ 620,00</label>
                </div>
              </td>
              <td>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                  <label class="form-check-label" for="inlineRadio2">R$ 622,00</label>
                </div>
              </td>
            </tr>
    </tbody>
    <tfoot>
      <tr class = "bg-danger">
        <td colspan="3" align="center"><b>Total</b></td>
        <td><b>R$ 625,00</b></td>
        <td><b>R$ 625,00</b></td>
        <td><b>R$ 625,00</b></td>
        <td><b>R$ 625,00</b></td>
      </tr>
    </tfoot>
  </table>
  </div>    
  <div class="form-row">
    <div class="col-md-1">
      <a data-toggle='tooltip'title='voltar' class="btn btn-danger btn-center" href="/orcamento">
         Finalizar
         <span class="fa check"></span>
      </a>
    </div>
    <div class="col-md-1">
      <a data-toggle='tooltip'title='voltar' class="btn btn-danger btn-center" href="/orcamento">
         Voltar
         <span class="fa fa-undo"></span>
      </a>
    </div>
  </div>
</div>