<div class="container">
  <div class="row header-pager">
    <div class="col-11">
      <h1><?php echo $this->orcamentoDetalhado[0]->nomeOrc ?></h1>
    </div>
  </div>
  <hr>
  <form action="/proposta/<?php echo $this->orcamentoDetalhado[0]->idOrc ?>/aprovar" method="post" accept-charset="utf-8">
  <div style="overflow-x:auto;">
    <table class="table table-striped table-bordered table-sm dtHorizontal" cellspacing="" width="100%">
    <?php
      $fornecedora = array();
      echo "
      <thead>
        <tr>
        <th>Produto</th>
        <th>Und</th>
        <th>Qtd</th>";
      $i = 0;
      $total;
      foreach($this->orcamentoDetalhado as $orcamento) {
        if ($orcamento->valor != "" && !isset($fornecedora[$orcamento->fornecedora])) {
          $fornecedora[$orcamento->fornecedora] = $i++;
          $total[$orcamento->fornecedora] = 0;
          echo "<th>
                  <input type='radio' name='idProposta' value='$orcamento->idProp' required> 
                  $orcamento->fornecedora
                </th>";
        }        
      }

      echo " 
        </tr>
      </thead>
      <tbody>";
      
      foreach ($this->orcamentoDetalhado as $orcamento) {
        if (!isset($produtos[$orcamento->idOrdOrc])) {
          $produtos[$orcamento->idOrdOrc] = 1;
          echo "<tr>      
                  <td>$orcamento->nomeProd</td>
                  <td>$orcamento->undProd</td>
                  <td>$orcamento->qtdProd</td>";

          if (isset($fornecedora[$orcamento->fornecedora])) {
            $i = 0;
            foreach ($this->orcamentoDetalhado as $orcamento2) {
              if ($orcamento->idOrdOrc == $orcamento2->idOrdOrc && $i == $fornecedora[$orcamento2->fornecedora]) {
                $i++; 
                $total[$orcamento2->fornecedora] += $orcamento2->valor;
                echo "<td>
                        <div class='form-check form-check-inline'>
                          <!-- <input class='form-check-input' type='radio' name='orc_$orcamento2->idOrdOrc' 
                          id='orc_$orcamento2->idOrdOrc'> -->
                          <label class='form-check-label' for='orc_$orcamento2->idOrdOrc'>$orcamento2->valor</label>
                        </div>
                      </td>";
              }
            }
          }                
        }

        echo "</tr>";
      }    

      echo "
      </tbody>";
      
      echo "
      <tfoot>
        <tr class = 'bg-danger'>
          <td colspan='3' align='center'><b>Total</b></td>";
          if (!empty($total))
            foreach ($total as $t) {
              echo "<td><b>R$ $t</b></td>";
            }
      echo "
        </tr>
      </tfoot>";
      
      ?>
    </table>
  </div>  

  <div class="form-row mt-2">
    <div class="col-md-1 mr-3">
      <button data-toggle='tooltip' type="submit" title='Aprovar proposta selecionada' class="btn btn-danger btn-center">
        Aprovar
        <span class="fa fa-check"></span>
      </button>
    </div>
    <div class="col-md-1">
      <a data-toggle='tooltip'title='voltar' class="btn btn-danger btn-center" href="/orcamento/listar">
        Voltar
        <span class="fa fa-undo"></span>
      </a>
    </div>
  </div>
  </form>
</div>