<div class="container">
  <div class="form-border">
    <form action="" method="post" accept-charset="utf-8" class="form-content border">
      
      <div class="row">
        <div class="col-10">
          <h1><?php echo $this->title ?></h1>
        </div>
        <div class="col-2 alingMiddle">
          <div <?php echo "class='". ($this->orcamentoAberto == 1 ? "orcamentoAberto": "orcamentoFechado") ."'" ?> >
            <?php echo $this->orcamentoAberto == 1 ? "orcamento aberto": "orcamento fechado" ."'" ?>
          </div>
        </div>
      </div>
      <hr/>

      <div class="form-row">
        <div class="col-md-4">
          <label class="col-form-label">Produto</label>
        </div>
        <div class="col-md-2">
          <label class="col-form-label">Und medida</label>
        </div>
        <div class="col-md-2">
          <label class="col-form-label">Quantidade</label>
        </div>
        <div class="col-md-2">
          <label class="col-form-label">Valor</label>
        </div>
      
        <?php 
          foreach ($this->orcamentoDetalhado as $orcamento) {
            echo "
            <div class='col-md-4'>
              <input type='text' class='form-control input-lg' value='$orcamento->nomeProd' readonly />
            </div>
            <div class='col-md-2'>
              <input type='text' class='form-control input-lg' value='$orcamento->undProd' readonly />
            </div>
            <div class='col-md-2'>
              <input type='number' class='form-control input-lg' value='$orcamento->qtdProd' readonly />
            </div>
            <div class='col-md-2'>
              <input type='number' name='valor[]' class='form-control input-lg' required />
            </div>       
            <div style='width: 100%; padding-bottom: 10px;'>
              <input type='number' name='id_ord_orc[]' value='$orcamento->idOrdem' readonly required hidden/>
            </div>     
            ";
          }
        ?>
      
        <div class="col-md-4">
          <a data-toggle="tooltip" type="submit" title="Salvar" href="" name="cadastrar" class="btn btn-danger mt-3">
            Enviar Proposta
            <span class="fa fa-save"></span>
          </a>
          <a data-toggle="tooltip" title="Cancelar" href="/orcamento/listar" class="btn btn-danger mt-3 ">
            Cancelar
            <span class="fa fa-times"></span>
          </a>
        </div>

      </div>
    </form>
  </div>
</div>