<div class="container-fluid">
  <div class="row icones">
    <div class="col-6 col-sm-6 col-md-4 text-center">
      <a href="/orcamento/cadastrar">
        <img src="/assets/img/cadastrar.png" height="80">
        <h5 class="mt-2 text-dark">Cadastrar Orçamento</h5>
      </a>
    </div>
    <div class="col-6 col-sm-6 col-md-4 text-center">
      <a href="/orcamento/listar">
        <img src="/assets/img/listar.png" height="80">
          <h5 class="mt-2 text-dark">Listar Orçamentos</h5>
      </a>
    </div>
    <div class="col-6 col-sm-6 col-md-4 text-center">
      <a href="/orcamento/aprovar">
        <img src="/assets/img/listar2.png" height="80">
          <h5 class="mt-2 text-dark">Aprovar Orçamentos</h5>
      </a>
    </div>
  </div>
</div>