<div class="container">
  <div class="row header-pager">
    <div class="col-6">
      <h1>Orçamentos</h1>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-11">
      <h5 class="text-left mt-2">Em andamento</h5>
    </div>
    <div class="col-md-1">
      <a data-toggle='tooltip'title='Voltar' class="btn btn-danger btn-center" href="/orcamento">
         <span class="fa fa-undo"></span>
      </a>
    </div>
  </div>
  <hr>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
      <tr>
        <th scope="col">Nº</th>
        <th scope="col">Nome Orçamento</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
         <?php 
          $i = 0;

          //foreach ($this->listaProdutos as $produto) {
            $btnDetalhar = "<a data-toggle='tooltip' title='Detalhar Oraçamento' href=''
                            <button mettod type='submit' name='detalhar' class='btn btn-danger btn-block'>
                              <span class='fa fa-info'></span>
                            </button>
                           </a>";
            $btnAlterar = "<a data-toggle='tooltip' title='Editar' href=''
                            <button type='submit' name='alterar' class='btn btn-danger btn-block'>
                              <span class='fa fa-pencil'></span>
                            </button>
                           </a>";
            $btnResponder = "<a data-toggle='tooltip' title='Responder Orçamento' href='/orcamento/aprovar'
                            <button type='submit' name='responder' class='btn btn-danger btn-block'>
                              <span class='fa fa-reply'></span>
                            </button>
                           </a>";
        
            $i++;

            echo "
            <tr>
            <td> <b>$i</b></td>
              <td>Nome Orçamento</td>
              <td width='5%'>$btnDetalhar</td>
              <td width='5%'>$btnAlterar</td>
              <td width='5%'>$btnResponder</td>
            </tr>";
         // }
        ?>
    </tbody>
  </table>
  </div>
  <hr>
  <h5 class="text-left">Meus Orçamentos Finalizados</h5>
  <hr>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
      <tr>
        <th scope="col">Nº</th>
        <th scope="col">Nome Orçamento</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
         <?php 
          $i = 0;

          //foreach ($this->listaProdutos as $produto) {
            $btnDetalhar = "<a data-toggle='tooltip' title='Detalhar Oraçamento' href=''
                            <button mettod type='submit' name='detalhar' class='btn btn-danger btn-block'>
                              <span class='fa fa-info'></span>
                            </button>
                           </a>";
            $i++;

            echo "
            <tr>
              <td> <b>$i</b></td>
              <td>Nome Orçamento</td>
              <td width='5%'></td>
              <td width='5%'></td>
              <td width='5%'>$btnDetalhar</td>
            </tr>";
         // }
        ?>
    </tbody>
  </table>
          </div>
</div>