<div class="container">
  <div class="row header-pager">
    <div class="col-6">
      <h1>Orçamentos</h1>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-11">
      <h5 class="text-left mt-2">Em andamento</h5>
    </div>
    <div class="col-md-1">
      <a data-toggle='tooltip'title='Voltar' class="btn btn-danger btn-center" href="/orcamento">
        Voltar
        <span class="fa fa-undo"></span>
      </a>
    </div>
  </div>
  <hr>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
      <tr>
        <th scope="col">Nº</th>
        <th scope="col">Nome Orçamento</th>
        <th scope="col">Inicio</th>
        <th scope="col">Termino</th>
        <th scope="col">Qtd. Prod.</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <?php 
        foreach ($this->listaOrcamentos as $orcamento) {
          if ($orcamento->ativo) {
            $btnDetalhar = "<a data-toggle='tooltip' title='Detalhar Oraçamento' class='btn btn-danger btn-block'
                              href='/orcamento/listar/$orcamento->id' name='detalhar' >
                              <span class='fa fa-external-link'></span>
                            </a>";
            $btnAlterar = "<a data-toggle='tooltip' title='Editar' class='btn btn-danger btn-block'
                            href='' name='alterar' >
                            <span class='fa fa-pencil'></span>
                           </a>";   

            echo "
            <tr>
              <th scope='row'>$orcamento->id</th>
              <td>$orcamento->nome</td>
              <td>$orcamento->vigencia_inicio</td>
              <td>$orcamento->vigencia_fim</td>
              <td>$orcamento->qtdProdutos</td>
              <td width='5%'>$btnDetalhar</td>
              <td width='5%'>$btnAlterar</td>
            </tr>";
          }
        } 
      ?>
    </tbody>
  </table>
  </div>
  <hr>
  <h5 class="text-left">Finalizados</h5>
  <hr>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
      <tr>
        <th scope="col">Nº</th>
        <th scope="col">Nome Orçamento</th>
        <th scope="col">Inicio</th>
        <th scope="col">Termino</th>
        <th scope="col">Qtd. Prod.</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <?php 
        $btnDetalhar = "<a data-toggle='tooltip' title='Detalhar Oraçamento' class='btn btn-danger btn-block'
                          href='' name='detalhar' >
                          <span class='fa fa-external-link'></span>
                        </a>";

        foreach ($this->listaOrcamentos as $orcamento) {
          if (!$orcamento->ativo) {
            echo "
            <tr>
              <th scope='row'>$orcamento->id</th>
              <td>$orcamento->nome</td>
              <td>$orcamento->vigencia_inicio</td>
              <td>$orcamento->vigencia_fim</td>
              <td>$orcamento->qtdProdutos</td>
              <td width='5%'>$btnResponder</td>
            </tr>";
          }
        }
      ?>
    </tbody>
  </table>
  </div>
</div>