<div class="container">
  <div class="row header-pager">
    <div class="col-11">
      <h1><?php echo $this->orcamentoDetalhado[0]->nomeOrc ?></h1>
    </div>
  </div>
  <hr>
  <form action="/proposta/<?php echo $this->orcamentoDetalhado[0]->idOrc ?>/aprovar" method="post" accept-charset="utf-8">
  <div style="overflow-x:auto;">
    <table class="table table-striped table-bordered table-sm dtHorizontal" cellspacing="" width="100%">
    <?php
      $fornecedora = array();
      echo "
      <thead>
        <tr>
        <th>Produto</th>
        <th>Und</th>
        <th>Qtd</th>";
      $i = 0;
      $total;
      $propAceita;
      $iterador = 0;
      foreach($this->orcamentoDetalhado as $orcamento) {
        if (!isset($fornecedora[$orcamento->fornecedora])) {
          $iterador++;
          $fornecedora[$orcamento->fornecedora] = $i++;
          $total[$orcamento->fornecedora] = 0;
          if ($orcamento->aceita == 1) {
            echo "<th style='background-color: #58D68D;'>$orcamento->fornecedora</th>";
            $propAceita = $iterador;
          }
          else 
            echo "<th>$orcamento->fornecedora</th>";
        }        
      }

      echo " 
        </tr>
      </thead>
      <tbody>";
      
      foreach ($this->orcamentoDetalhado as $orcamento) {
        if (!isset($produtos[$orcamento->idOrdOrc])) {
          $produtos[$orcamento->idOrdOrc] = 1;
          echo "<tr>      
                  <td>$orcamento->nomeProd</td>
                  <td>$orcamento->undProd</td>
                  <td>$orcamento->qtdProd</td>";

          $i = 0;
          foreach ($this->orcamentoDetalhado as $orcamento2) {
            if ($orcamento->idOrdOrc == $orcamento2->idOrdOrc && $i == $fornecedora[$orcamento2->fornecedora]) {
              $i++; 
              $total[$orcamento2->fornecedora] += $orcamento2->valor;
              $style = $orcamento2->aceita == 1 ? "style='background-color: #ABEBC6;'": ""; 
              echo "<td $style>
                      <div class='form-check form-check-inline'>
                        <!-- <input class='form-check-input' type='radio' name='orc_$orcamento2->idOrdOrc' 
                        id='orc_$orcamento2->idOrdOrc'> -->
                        <label class='form-check-label' for='orc_$orcamento2->idOrdOrc'>$orcamento2->valor</label>
                      </div>
                    </td>";
            }
          }                
        }

        echo "</tr>";
      }    

      echo "
      </tbody>";
      
      echo "
      <tfoot>
        <tr class = 'bg-danger'>
          <td colspan='3' align='center'><b>Total</b></td>";
          $i = 0;
          foreach ($total as $t) {
            $i++;
            if ($i == $propAceita)
              echo "<td style='background-color: #52BE80;'><b>R$ $t</b></td>";
            else
              echo "<td><b>R$ $t</b></td>";
          }
      echo "
        </tr>
      </tfoot>";
      
      ?>
    </table>
  </div>  

  <div class="form-row mt-2">
    <div class="col-md-1">
      <a data-toggle='tooltip'title='voltar' class="btn btn-danger btn-center" href="/orcamento/listar">
        Voltar
        <span class="fa fa-undo"></span>
      </a>
    </div>
  </div>
  </form>
</div>