<div class="container">
  <div class="form-border col-12 col-sm-12 border">
    <form action="<?php //echo isset($this->produto->id) ? '' : '/produtos/cadastrar'?>" method="post" accept-charset="utf-8" class="form-content border">
    <div class="row">
      <div class="col-11">
        <h2 class="text-left">Meu Perfil</h2>
      </div>
      <div class="col-1">
        <img src="/assets/img/adm.png" height="50">
      </div>
     <hr>   
    </form>
  </div>
</div>
