<div class="container">
  <div class="form-border col-12 col-sm-12 border">
    <form action="<?php //echo isset($this->produto->id) ? '' : '/produtos/cadastrar'?>" method="post" accept-charset="utf-8" class="form-content border">
    <div class="row">
      <div class="col-11">
        <h2 class="text-left">Meu Perfil</h2>
      </div>
      <div class="col-1">
        <img src="/assets/img/adm.png" height="50">
      </div>
    </div>
     <hr>
     <div class="form-row">
        <div class="col-md-4">
          <label class="col-form-label"> Usuário </label>  
          <input type="text" id="login" name="login" placeholder="Usuário de login" autofocus required class="form-control" 
          value="">
          <div id="uname_response" class="response"></div>
      </div>
      <div class="col-md-8">
          <label class="col-form-label"> Nome </label>  
          <input type="text" name="nome" placeholder="Nome da Empresa" autofocus required class="form-control" 
          value="">
        </div>
     </div>
      <div class="form-row">
        
        <div class="col-md-3">
          <label class="col-form-label">CPF </label>
          <input type="text" name="num_documento" placeholder="CNPJ/CPF" required class="form-control" 
            value="">
        </div>
        <div class="col-md-3">
        <label class="col-form-label" for="telefone"> Telefone </label>
        <input type="text" name="telefone" id="telefone" class="form-control" required placeholder="(00) 90000-000"
          value=""/>
      </div>
      <div class="col-md-6">
        <label class="col-form-label" for="email"> E-mail </label>
        <input type="email" name="email" id="email" class="form-control" required placeholder="meuemail@email.com"
          value=""/>
      </div>  
     </div>
    <div class="form-row">      
      <div class="col-md-11">
        <label class="col-form-label"> Endereço </label>
        <input type="text" name="endereco" id="endereco" class="form-control input-lg" onkeyup="UpperCase(this)"
          required placeholder="Rua ..." value="" />
      </div>
      <div class="col-md-1">
        <label class="col-form-label"> Nº </label>
        <input type="text" name="numero" id="numero" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="000" value="" />
      </div>
    </div> 
    <div class="form-row">
      <div class="col-md-5">
        <label class="col-form-label"> CEP </label>
        <input type="text" name="cep" id="cep" class="form-control input-lg" onkeyup="LowerCase(this)"
                               required placeholder="00000-000" value="" />
      </div>
      <div class="col-md-5">
        <label class="col-form-label"> Cidade </label>
        <input type="text" name="cidade" id="cidade" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="Sua cidade..." value="" />
      </div>
      <div class="col-md-2">
        <label class="col-form-label"> UF </label>
        <select name="UF" id="UF" class="form-control" required>
          <option value="" selected hidden>CE</option>
        </select>
      </div>
    </div>   
    </form>
</div>
