<div class="container-fluid">
  <div class="row icones">
  <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/adm">
        <img src="/assets/img/adm.png" height="80">
          <h5 class="mt-2 text-dark">Meu Perfil</h5>
      </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/usuario">
        <img src="/assets/img/user.png" height="80">
          <h5 class="mt-2 text-dark">Gerenciar Usuários</h5>
      </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/orcamento">
        <img src="/assets/img/orcamento.png" height="80">
          <h5 class="mt-2 text-dark">Gerenciar Orçamentos</h5>
      </a>
    </div>
  </div>
  <div class="row icones">
  <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/fornecedora/listar_atualizar">
        <img src="/assets/img/fornecedora.png" height="80">
          <h5 class="mt-2 text-dark">Gerenciar Fornecedoras</h5>
      </a>
    </div>
  <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/produtos">
        <img src="/assets/img/produtos.png" height="80">
          <h5 class="mt-2 text-dark">Gerenciar Produtos</h5>
      </a>
    </div>
    
  </div>    
</div>