<div class="container-fluid">
  <div class="row icones">
    <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/produtos">
        <img src="/assets/img/produtos.png" height="80">
          <h5 class="mt-2 text-dark">Gerenciar Produtos</h5>
      </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/orcamento/cadastrar">
        <img src="/assets/img/orcamento.png" height="80">
          <h5 class="mt-2 text-dark">Cadastrar Orçamentos</h5>
      </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 text-center">
      <a href="/fornecedora/listar_atualizar">
        <img src="/assets/img/fornecedora.png" height="80">
          <h5 class="mt-2 text-dark">Gerenciar Fornecedoras</h5>
      </a>
    </div>
  </div>
</div>