<div class="container">
  <div class="form-border col-12 col-sm-12 border">
    <form action="<?php //echo isset($this->produto->id) ? '' : '/produtos/cadastrar'?>" method="post" accept-charset="utf-8" class="form-content border">
      <h2 class="text-left">Cadastrar Fornecedora</h2>
      <hr>
      <div class="form-row">
        <div class="col-md-6">
         <label class="col-form-label"> Nome </label>  
        <input type="text" name="nome" placeholder="Nome da Empresa" autofocus required class="form-control" 
          value="">
        </div>
        <div class="col-md-6">
           <label class="col-form-label"> Nome Fantasia </label>
          <input type="text" name="nome" placeholder="Nome Fantasia" required class="form-control" 
          value="">
        </div>
     </div>
    <div class="form-row">
        <div class="col-md-3">
           <label class="col-form-label"> CNPJ </label>
          <input type="text" name="cnpj" placeholder="CNPJ" required class="form-control" 
          value="">
        </div>
        <div class="col-md-3">
          <label class="col-form-label" for="telefone"> Telefone </label>
          <input type="text" name="telefone" id="telefone" class="form-control" required 
                               value=""/>
        </div>
      <div class="col-md-5">
        <label class="col-form-label"> Endereço </label>
        <input type="text" name="endereco" id="endereco" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="Rua ..." value="" />
      </div>
      <div class="col-md-1">
        <label class="col-form-label"> Nº </label>
        <input type="text" name="numero" id="numero" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="" value="" />
      </div>
    </div> 
    <div class="form-row">
      <div class="col-md-5">
        <label class="col-form-label"> Cidade </label>
        <input type="text" name="cidade" id="cidade" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="Sobral" value="" />
      </div>
      <div class="col-md-2">
        <label class="col-form-label"> UF </label>
        <input type="text" name="uf" id="uf" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="CE" value=" "/>
      </div>
      <div class="col-md-5">
        <label class="col-form-label"> País </label>
        <input type="text" name="pais" id="pais" onkeyup="UpperCase(this)" class="form-control input-lg" 
                               placeholder="Brasil" onkeyup="UpperCase(this)" value=""/>
      </div>
    </div>
    <hr>
    <h5 class="text-left">Selecione Produtos que Fornece</h5>
    <hr>

      <p><input type="checkbox" id="checkTodos" name="checkTodos"> Selecionar Todos</p>
        
      <p><input type="checkbox" value="1"> Areia</p>
      <p><input type="checkbox" value="2"> Ferro</p>
      <p><input type="checkbox" value="3"> Telha</p>
      <p><input type="checkbox" value="4"> Tijolo</p>
      <p><input type="checkbox" value="5"> Madeira</p>

    <div class="form-row">
      <div class="col-md-12 ">
        <button data-toggle="tooltip" title="Salvar" type="submit" name="cadastrar" class="btn btn-danger mt-3">
          <span class="fa fa-save"></span>
        </button>
      </div>
    </div>
  </form>
</div>
<script>
    //Mascara Telefone
    $(document).ready(function() {
        $("#telefone").mask("(00) 0000-00009")
            
        $("#telefone").blur(function(event) {
            if ($(this).val().length == 15)
                $("#telefone").mask("(00) 0 0000-0000")
            else
                $("#telefone").mask("(00) 0000-00009")
        })
    })
   //CheckBox 
    $("#checkTodos__").change(function () {
    $("input:checkbox").prop('checked', $(this).prop("checked"));
    });

    $("#checkTodos__").click(function(){
        $('input:checkbox').not(this).prop('checked', this.checked);
    });

    var checkTodos = $("#checkTodos");
    checkTodos.click(function () {
        if ( $(this).is(':checked') ){
            $('input:checkbox').prop("checked", true);
        }else{
            $('input:checkbox').prop("checked", false);
        }
    });
</script>