<div class="container">
  <div class="form-border col-12 col-sm-12 border">
    <form action="" method="post" accept-charset="utf-8" class="form-content border">
      <h2 class="text-left">Cadastrar Fornecedora</h2>
      <hr>
      <div class="form-row">
        <div class="col-md-6">
          <label class="col-form-label"> Usuário </label>  
          <input type="text" id="login" name="login" placeholder="Usuário de login" autofocus required class="form-control" 
          value="">
          <div id="uname_response" class="response"></div>
        </div>
        <div class="col-md-3">
          <label class="col-form-label"> Senha </label>
          <input type="password" id="senha" name="senha" placeholder="" required class="form-control" 
            value="">
        </div>
        <div class="col-md-3">
          <label class="col-form-label"> Repita sua senha </label>
          <input type="password" id="repsenha" name="repsenha" placeholder="" required class="form-control" 
            value="">
          <div id="repsenha_response" class="response"></div>
        </div>
     </div>
      <div class="form-row">
        <div class="col-md-6">
          <label class="col-form-label"> Nome </label>  
          <input type="text" name="nome" placeholder="Nome da Empresa" autofocus required class="form-control" 
          value="">
        </div>
        <div class="col-md-3">
          <label class="col-form-label"> CNPJ/CPF </label>
          <input type="text" name="num_documento" placeholder="CNPJ/CPF" required class="form-control" 
            value="">
        </div>
        <div style="padding-top: 30px;">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="tipo_documento" value="CNPJ" checked>
            <label class="form-check-label"> CPNJ </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="tipo_documento" value="CPF">
            <label class="form-check-label"> CPF </label>
          </div>
        </div>
     </div>
    <div class="form-row">      
      <div class="col-md-3">
        <label class="col-form-label" for="telefone"> Telefone </label>
        <input type="text" name="telefone" id="telefone" class="form-control" required placeholder="(00) 90000-000"
          value=""/>
      </div>
      <div class="col-md-3">
        <label class="col-form-label" for="email"> E-mail </label>
        <input type="email" name="email" id="email" class="form-control" required placeholder="meuemail@email.com"
          value=""/>
      </div>  
      <div class="col-md-5">
        <label class="col-form-label"> Endereço </label>
        <input type="text" name="endereco" id="endereco" class="form-control input-lg" onkeyup="UpperCase(this)"
          required placeholder="Rua ..." value="" />
      </div>
      <div class="col-md-1">
        <label class="col-form-label"> Nº </label>
        <input type="text" name="numero" id="numero" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="000" value="" />
      </div>
    </div> 
    <div class="form-row">
      <div class="col-md-5">
        <label class="col-form-label"> CEP </label>
        <input type="text" name="cep" id="cep" class="form-control input-lg" onkeyup="LowerCase(this)"
                               required placeholder="00000-000" value="" />
      </div>
      <div class="col-md-5">
        <label class="col-form-label"> Cidade </label>
        <input type="text" name="cidade" id="cidade" class="form-control input-lg" onkeyup="UpperCase(this)"
                               required placeholder="Sua cidade..." value="" />
      </div>
      <div class="col-md-2">
        <label class="col-form-label"> UF </label>
        <select name="UF" id="UF" class="form-control" required>
          <option value="" selected hidden>Selecione...</option>
          <option value="AC">AC</option>
          <option value="AL">AL</option>
          <option value="AM">AM</option>
          <option value="AP">AP</option>
          <option value="BA">BA</option>
          <option value="CE">CE</option>
          <option value="DF">DF</option>
          <option value="ES">ES</option>
          <option value="GO">GO</option>
          <option value="MA">MA</option>
          <option value="MG">MG</option>
          <option value="MS">MS</option>
          <option value="MT">MT</option>
          <option value="PA">PA</option>
          <option value="PB">PB</option>
          <option value="PE">PE</option>
          <option value="PI">PI</option>
          <option value="PR">PR</option>
          <option value="RJ">RJ</option>
          <option value="RN">RN</option>
          <option value="RO">RO</option>
          <option value="RR">RR</option>
          <option value="RS">RS</option>
          <option value="SC">SC</option>
          <option value="SE">SE</option>
          <option value="SP">SP</option>
          <option value="TO">TO</option>
        </select>
      </div>
    </div>

    <div class="form-row">
      <div class="col-md-12 ">
        <button data-toggle="tooltip" title="Salvar" type="submit" name="cadastrar" class="btn btn-danger mt-3">
          Cadastrar
          <span class="fa fa-save"></span>
        </button>
      </div>
    </div>
  </form>
</div>
<script>
  $(document).ready(function() {
    $("#login").keyup(function() {
      var uname = $("#login").val().trim();

      if(uname != '') {
        $("#uname_response").show();
        
        $.ajax({
          url: '/login/verificarUsuario/' + uname,
          type: 'post',
          success: function(response) {
            if(response == 1) {
              $("#uname_response").html("<span class='not-exists' style='color: red; font-weight: 600;'>* Este usuário ja existe </span>");
            } else {
              $("#uname_response").html("");
            }
          }
        });
      } else {
        $("#uname_response").html("");
        $("#uname_response").hide();
      }
    });

    $("#repsenha").keyup(function() {
      var senha = $("#senha").val();
      var repsenha = $("#repsenha").val();

      if(repsenha != '') {
        if(senha != repsenha ) {
          $("#repsenha_response").html("<span class='not-exists' style='color: red; font-weight: 600;'>* Senhas diferentes </span>");
        } else {
          $("#repsenha_response").html("");
        }

        $("#repsenha_response").show();
      } else {        
        $("#repsenha_response").hide();
        $("#repsenha_response").html("");
      }
    });

    // $("#telefone").mask("(00) 0000-00009")
        
    // $("#telefone").blur(function(event) {
    //   if ($(this).val().length == 15)
    //     $("#telefone").mask("(00) 0 0000-0000")
    //   else
    //     $("#telefone").mask("(00) 0000-00009")
    // })
  });

  //CheckBox 
  // $("#checkTodos__").change(function () {
  //   $("input:checkbox").prop('checked', $(this).prop("checked"));
  // });

  // $("#checkTodos__").click(function(){
  //     $('input:checkbox').not(this).prop('checked', this.checked);
  // });

  // var checkTodos = $("#checkTodos");
  // checkTodos.click(function () {
  //     if ( $(this).is(':checked') ){
  //         $('input:checkbox').prop("checked", true);
  //     } else{
  //         $('input:checkbox').prop("checked", false);
  //     }
  // });
</script>