<div class="container">
  <div class="form-border border col-10 col-md-4">
    <form action="/login/autenticar" method="post" accept-charset="utf-8" class="form-content border">
      <h4 class="form-login-heading text center">Esqueci Minha Senha</h4>
      <hr>
      <div class="form-group">
        <input type="text" name="email" placeholder="seu email" class="form-control form-control-fa" required autofocus>
      </div>
      <div class="form-group custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck1">
        <label class="custom-control-label" for="customCheck1">Não sou robor</label>
      </div>
      <button class="btn btn-danger btn-block mt-3" type="submit" role="button">
        Enviar
      </button>
    </form>
  </div>
</div>