<div class="container">
  <?php
    if (isset($this->aviso)) {
      echo '<div class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong>'. $this->aviso .'
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>';
    
      unset($this->aviso);
    }    
  ?>

  <div class="form-border border col-10 col-md-4">
    <form action="/login/autenticar" method="post" accept-charset="utf-8" class="form-content border">
      <h4 class="form-login-heading text-center">Login</h4>
      <hr>
      <div class="form-group">
        <input type="text" name="login" placeholder="usuário" class="form-control form-control-fa" required autofocus>
        <i class="fa fa-user"></i>
      </div>
      <div class="form-group">
        <input type="password" name="senha" placeholder="senha" class="form-control form-control-fa"  required>
        <i class="fa fa-lock"></i>
      </div>
      <div class="form-group custom-control custom-checkbox checkbox-danger">
        <input type="checkbox" class="custom-control-input" id="customCheck1">
        <label class="custom-control-label" for="customCheck1">Manter-me conectado</label>
      </div>
      <button class="btn btn-danger btn-block mt-3" type="submit" role="button">
        Entrar
      </button>
      <div class="text-center">
        <a  href="/login/cadastrar">Cadastrar-me</a>
      </div>
      <div class="text-center">
        <a  href="/login/esqueci-senha">Esqueci Minha Senha</a>
      </div>
    </form>
  </div>
</div>