<div class="container">
  <?php
    if (isset($this->aviso)) {
      echo '<div class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong>'. $this->aviso .'
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>';
    
      unset($this->aviso);
    }    
  ?>

  <div class="row header-pager">
    <div class="col-6">
      <h1>Fornecedoras</h1>
    </div>
  </div>

  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
    <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
      <thead class="bg-danger">
        <tr>
          <th scope="col">Nº</th>
          <th scope="col">Nome</th>
          <th scope="col">Cadastrada Em</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <?php 
          foreach($this->fornecedoras as $fornecedora) {
            $btnDados = "<a data-toggle='tooltip' title='Visualizar dados' href='/perfil/$fornecedora->id'
                            name='dados' class='btn btn-danger btn-block'>
                            <span class='fa fa-database'></span>
                        </a>";

            if ($fornecedora->ativo) {
              echo "
              <tr>
                <td scope='row'>$fornecedora->id</th>
                <td>$fornecedora->nome</td>
                <td>$fornecedora->criado_em_formatado</td>
                <td width='5%'>$btnDados</td>
              </tr>";
            }
          }
        ?>
      </tbody>
    </table>
  </div>

  <hr>
  <h5 class="text-left">Pendentes a validar</h5>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
    <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
      <thead class="bg-danger">
        <tr>
          <th scope="col">Nº</th>
          <th scope="col">Nome</th>
          <th scope="col">Cadastrada Em</th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <?php 
          foreach($this->fornecedoras as $fornecedora) {
            if (!$fornecedora->ativo) {
              $btnAprovar = "<a data-toggle='tooltip' title='Aprovar' href='/fornecedora/$fornecedora->id/aprovar'
                                name='alterar' class='btn btn-danger btn-block'>
                                <span class='fa fa-check'></span>
                            </a>";              
              $btnRecusar = "<a data-toggle='tooltip' title='Recusar' href='/fornecedora/$fornecedora->id/recusar'
                                name='excluir' class='btn btn-danger btn-block'>
                                <span class='fa fa-close'></span>
                            </a>";
              $btnDados = "<a data-toggle='tooltip' title='Visualizar dados' href='/perfil/$fornecedora->id'
                              name='alterar' class='btn btn-danger btn-block'>
                              <span class='fa fa-database'></span>
                          </a>";

              echo "
              <tr>
                <td scope='row'>$fornecedora->id</th>
                <td>$fornecedora->nome</td>
                <td>$fornecedora->criado_em_formatado</td>
                <td width='5%'>$btnAprovar</td>
                <td width='5%'>$btnRecusar</td>
                <td width='5%'>$btnDados</td>
              </tr>";
            }
          }
        ?>
      </tbody>
    </table>
  </div>
</div>