<div class="container">
  <div class="row header-pager">
    <div class="col-6">
      <h1>Fornecedoras</h1>
    </div>
  </div>

  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
      <tr>
        <th scope="col">Nº</th>
        <th scope="col">Nome Fantasia</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
         <?php 
          $i = 0;

          //foreach ($this->listaProdutos as $produto) {
            $btnDados = "<a data-toggle='tooltip' title='Dados' href=''
                            <button mettod type='submit' name='dados' class='btn btn-danger btn-block'>
                              <span class='fa fa-database'></span>
                            </button>
                           </a>";
            $btnAlterar = "<a data-toggle='tooltip' title='Editar' href=''
                            <button type='submit' name='alterar' class='btn btn-danger btn-block'>
                              <span class='fa fa-pencil'></span>
                            </button>
                           </a>";
            $i++;

            echo "
            <tr>
              <td><b>$i<b/></th>
              <td>Nome Fantasia</td>
              <td width='5%'>$btnDados</td>
              <td width='5%'>$btnAlterar</td>
            </tr>";
         // }
        ?>
    </tbody>
  </table>
          </div>
  <hr>
  <h5 class="text-left">Validar</h5>
  <hr>
  <div class="table-wrapper-scroll-y table-wrapper-scroll-x">
  <table cellspacing="0" class=" table table-striped table-hover table-sm" width="100%">
    <thead class="bg-danger">
      <tr>
        <th scope="col">Nº</th>
        <th scope="col">Nome Fantasia</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
       <?php 
          $i = 0;

          //foreach ($this->listaProdutos as $produto) {
            $btnDados = "<a data-toggle='tooltip' title='Dados' href=''
                            <button mettod type='submit' name='alterar' class='btn btn-danger btn-block'>
                              <span class='fa fa-database'></span>
                            </button>
                           </a>";
            $btnValidar = "<a data-toggle='tooltip' title='Validar' href=''
                            <button type='submit' name='excluir' class='btn btn-danger btn-block'>
                              <span class='fa fa-check'></span>
                            </button>
                           </a>";
            $i++;

            echo "
            <tr>
              <td><b>$i</b></td>
              <td>Nome Fantasia</td>
              <td width='5%'>$btnDados</td>
              <td width='5%'>$btnValidar</td>
            </tr>";
         // }
        ?>
    </tbody>
  </table>
          </div>
</div>