<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="icon" href="/assets/img/more+.ico">    
    <style>
      a:hover {
	      color:#f00;
	}
    </style>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="/assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="/assets/js/popper.min.js" type="text/javascript"></script>
    <script src="/assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/assets/js/bootstrap-toggle.min.js" type="text/javascript"></script>
    <script src="/assets/js/select2.min.js" type="text/javascript"></script>
    <script src="/assets/js/jquery.mask.min.js" type="text/javascript"></script>

    <title><?php $this->getPageTitle('-') ?> More Mais</title>
  </head>
  <body>
    <?php require_once __DIR__ . "/menu.phtml" ?>

    <?php $this->content() ?>

    <?php //require_once __DIR__ . "/rodape.phtml" ?>
    
    <!--<script src="/assets/js/jquery.mask.mim.js"></script>
    <script src="/assets/js/jquery.js"></script>
    <script>
        $(function() {

            $('table > tbody > tr:odd').addClass('odd');

            $('table > tbody > tr').hover(function() {
                $(this).toggleClass('hover');
            });

            $('table > tbody > tr > td > :checkbox').bind('click change', function() {
                var tr = $(this).parent().parent();
                if ($(this).is(':checked')) $(tr).addClass('selected');
                else $(tr).removeClass('selected');
            });

            $("table")
                .tablesorter({
                    dateFormat: 'uk',
                    headers: {
                        0: {
                            sorter: false
                        },
                        5: {
                            sorter: false
                        }
                    }
                })
                .tablesorterPager({
                    container: $("#pager")
                })
                .bind('sortEnd', function() {
                    $('table > tbody > tr').removeClass('odd');
                    $('table > tbody > tr:odd').addClass('odd');
                });

        });

        $(document).ready(function() {
            $("#telefone").mask("(00) 0000-00009")

            $("#telefone").blur(function(event) {
                if ($(this).val().length == 15)
                    $("#telefone").mask("(00) 0 0000-0000")
                else
                    $("#telefone").mask("(00) 0000-00009")
            })
        })

    </script>-->

  </body>
</html>
