<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="icon" href="/assets/img/more+.ico">    
    <style>
      a:hover {
	      color:#f00;
	}
    </style>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="/assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="/assets/js/popper.min.js" type="text/javascript"></script>
    <script src="/assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/assets/js/bootstrap-toggle.min.js" type="text/javascript"></script>
    <script src="/assets/js/select2.min.js" type="text/javascript"></script>
    <script src="/assets/js/jquery.mask.min.js" type="text/javascript"></script>

    <title><?php $this->getPageTitle('-') ?> More Mais</title>
  </head>
  <body>
    <?php require_once __DIR__ . "/menu.phtml" ?>

    <?php require_once __DIR__ . "/alert.phtml" ?>

    <?php $this->content() ?>

    <?php //require_once __DIR__ . "/rodape.phtml" ?>

  </body>
</html>
